config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "ideas#index"
  resources :ideas do
    resources :reviews, only: [:create, :destroy]
    resources :likes, shallow: true, only: [:create, :destroy]
  end
  resources :users, only: [:new,:create,:edit,:update]
  resource :sessions, only: [:new,:create,:destroy]
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      if user.is_admin?
        can :manage, :all
      else
        can :read, :all
      end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities

    alias_action :create, :read, :update, :delete, :to => :crud

    can :crud, Idea do |idea|
      user == idea.user
    end

    can :crud, Review do |review|
      user == review.user
    end
    can :crud, User, id: user.id

    can :like, Idea do |idea|
      user.persisted? && idea.user != user
    end
    can :delete, Like do |like|
      like.user == user
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/idea.rb
class Idea < ApplicationRecord
    validates :title, presence: true
    has_many :reviews, dependent: :destroy
    belongs_to :user
    has_many :likes, dependent: :destroy
    has_many :likers, through: :favourites, source: :user
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :user
    belongs_to :idea
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :idea
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates :email, presence: true, :format => /@/ 
    has_many :ideas, dependent: :destroy
    has_many :reviews, dependent: :destroy
    has_many :likes, dependent: :destroy
    has_many :ideas, through: :favourites, source: :idea
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def authenticate_user!
        if !user_signed_in?
            flash[:notice] = "please Sign In first"
            redirect_to new_sessions_path
        end
    end

    def user_signed_in?
        current_user.present?
    end
    helper_method :user_signed_in?
    def current_user
        @current_user ||= User.find_by_id session[:user_id]
    end
    helper_method :current_user
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController

    before_action :authenticate_user!, except: [:show, :index]
    before_action :find_idea, only: [:show, :edit, :update, :destroy]
    before_action :authorize_user!, only: [:edit, :update, :destroy]
    def new
        @idea  = Idea.new
    end
    def create
        @idea  = Idea.new params.require(:idea).permit(:title, :description)
        @idea.user = User.find_by_id session[:user_id]
        if @idea.save
            redirect_to idea_path(@idea)
        else
            render :new
        end
    end

    def show
        @review = Review.new
        @reviews = Review.all.order(created_at: :desc)
        @like = @idea.likes.find_by(user: current_user)
    end

    def index
        @ideas = Idea.all.order(created_at: :desc)
    end

    def edit
    end

    def update
        @idea.update params.require(:idea).permit(:title, :description)
        redirect_to idea_path(@idea)
    end
    
    def destroy
        @idea.destroy
        redirect_to ideas_path
    end

    private
    def find_idea
        @idea = Idea.find params[:id]
    end
    def authorize_user!
        redirect_to root_path, alert: "Not Authorized! " unless can?(:crud, @idea) 
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def create
        @user = current_user
        @idea = Idea.find params[:idea_id]
        @like = Like.new(user: @user, idea: @idea)

        if can?(:like, @idea)
            if@like.save 
                flash.notice = "Added to liked ideas"
            else
                flash.alert = @like.errors.full_messages.join(', ')
            end
        else
            flash[:notice] = "you can not add it to likes"
        end
        redirect_to ideas_path
    end
    def destroy
        @like = current_user.likes.find params[:id]
        if can?(:delete, @like)
            @like.destroy
            flash.notice = "Product removed from likes"
        else
            flash.alert = "couldn't remove from likes"
        end
        redirect_to ideas_path
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

    before_action :authenticate_user!
    before_action :find_idea
    def create
        @review = Review.new params.require(:review).permit(:body)
        @review.idea = @idea
        @review.user = User.find_by_id session[:user_id]
        if @review.save
            redirect_to idea_path(@idea)
        end
    end
    def destroy
        @review = Review.find params[:id]
        if can?(:crud, @review)
            @review.destroy
            redirect_to idea_path(@idea.id)
        else
            redirect_to root_path, alert: "Not Authorized! "
        end
    end
    private
    def find_idea
        @idea = Idea.find params[:idea_id]
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
        
    end
    def create
        @user = User.find_by_email params[:email]
        if @user && @user.authenticate(params[:password])
            session[:user_id] = @user.id
            flash[:notice] = "Logged In"
            redirect_to root_path
        else
            flash[:notice] = "wrong password or email"
            render :new
        end
    end
    def destroy
        session[:user_id] = nil
        flash[:notice] = "Logged Out"
        redirect_to root_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
        @user = User.new
    end
    def create
        @user = User.new params.require(:user).permit(:name,:email,:password, :password_confirmation)
        if @user.save
            redirect_to root_path
        else
            render :new
        end
    end
    def edit
        @user  = User.find params[:id]
    end
    def update
        @user  = User.find params[:id]
        @user.update params.require(:user).permit(:name,:email)
        redirect_to root_path
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/ideas/edit.html.erb
<%=form_with model: @idea, url: idea_path(@idea), class:"m-3" do |f|%>
    <div class="mb-3">
        <%= f.label :title, class: "form-label"%>
        <%= f.text_field :title, class: "form-control"%>
    </div>
    <div class="mb-3">
        <%= f.label :description, class: "form-label"%>
        <%= f.text_area :description, class: "form-control"%>
    </div>
    <div class="d-grid justify-content-md-end">
        <%= f.submit class:"btn", id: "button"%>
    </div>
<% end %>

app/views/ideas/index.html.erb
<div class="container-fluid">
    <% @ideas.each do |idea|%>
    <div class="card-body border-top border-3 border-dark">
        <a href="<%= idea_path(idea)%>" class="card-title text-decoration-none text-reset fw-bold"><%= idea.title%></a>
        <p class="card-text"><%= idea.description%></p>
        <small>created <%= time_ago_in_words(idea.created_at)%> by <%= idea.user.name%></small>
        <small>
            <% if like.present? %>
                <%= button_to "Unlike", like_path(like), method: :delete %>
            <% else %>
                <%= button_to 'Like', idea_likes_path(idea), method: :post %>
            <% end %>
        </small>
    </div>
    <% end %>
</div>

app/views/ideas/new.html.erb
<%=form_with model: @idea, class:"m-3" do |f|%>
    <div class="mb-3">
        <%= f.label :title, class: "form-label"%>
        <%= f.text_field :title, class: "form-control"%>
    </div>
    <div class="mb-3">
        <%= f.label :description, class: "form-label"%>
        <%= f.text_area :description, class: "form-control"%>
    </div>
    <div class="d-grid justify-content-md-end">
        <%= f.submit class:"btn", id: "button"%>
    </div>
<% end %>

app/views/ideas/show.html.erb
<div class= "card">
    <div class="card-body">
        <h5 class="card-title border-top"> <%= @idea.title%></h5>
        <p class="card-text"><%= @idea.description%></p>
    </div>
    <div class="d-flex flex-row justify-content-end">
    <div class= "p-2">
        <a href="<%= edit_idea_path(@idea)%>" class="btn p-2" id="button">Edit</a>
    </div>
    <div class="p-2">
        <%= button_to "Delete", idea_path(@idea), method: :delete, class: "btn p-2", id:"button" %>
    </div>
    </div>
</div>
<%=form_with model:[@idea,@review], class:"" do |f|%>
    <div class="m-3">
        <%= f.label :body, class:"form-label"%>
        <%= f.text_area :body, class:"form-control"%>
    </div>
    <div class="m-3">
        <%= f.submit class:"btn", id:"button"%>
    </div>
<% end %>
<br>
<div class="m-3">
<h4>Riviews</h2>
    <% @reviews.each do |review|%>
    <div class="card-body">
        <p class="card-text"><%= review.body%></p>
        <%= button_to 'Delete', idea_review_path(@idea.id,review.id), method: :delete%>
    </div>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Quiz2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class= "container-fluid">
      <div class="navbar-brand ">
        <img src="https://image.shutterstock.com/z/stock-vector-brain-logo-silhouette-design-vector-template-think-idea-concept-brain-storm-power-thinking-brain-662421157.jpg" alt="" id="logo">
        <a class="navbar-brand fs-2 fw-bold" href="<%= root_path%>"> Idea Factory</a>
      </div>
        <button class="navbar-toggler navbar-light" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class ="collapse navbar-collapse justify-content-md-end" id="navbarNav">
          <ul class="navbar-nav d-flex flex-row">
            <% if (user_signed_in?)%>
            <li class="nav-item p-2">
              <a class="nav-link active fw-bold fs-4" href="<%= edit_user_path(current_user)%>">Hello <%= current_user.name%></a>
            </li>
            <li class="nav-item p-2">
              <%= button_to "Log out", sessions_path, method: :delete, class:"nav-link active btn",id:"button" %>
            </li>
            <% else%>
            <li class="nav-item p-2">
              <a class="nav-link active btn" id="button" href="<%= new_user_path%>">Sign UP</a>
            </li>
            <li class="nav-item p-2">
              <a class="nav-link active btn" id="button" href="<%= new_sessions_path%>">Sign In</a>
            </li>
            <% end %>
            <li class="nav-item p-2">
              <a class="nav-link active btn"id="button" aria-current="page" href="<%= new_idea_path %>">New Idea</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <% flash.each do |type, message| %>
    <div class="m-2 p-3 bg-warning text-dark ">
      <%= type + "-------" + message %>
    </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<%=form_with model: @user, url:user_path(@user), class:"m-3" do |f|%>
    <div class="mb-3">
        <%= f.label :name, class: "form-label"%>
        <%= f.text_field :name, class: "form-control"%>
    </div>
    <div class="mb-3">
        <%= f.label :email, class: "form-label"%>
        <%= f.email_field :email, class: "form-control"%>
    </div>
    <div class="d-grid justify-content-md-end">
        <%= f.submit class:"btn", id: "button"%>
    </div>
<% end %>

app/views/users/new.html.erb
<%=form_with model: @user, class:"m-3" do |f|%>
    <div class="mb-3">
        <%= f.label :name, class: "form-label"%>
        <%= f.text_field :name, class: "form-control"%>
    </div>
    <div class="mb-3">
        <%= f.label :email, class: "form-label"%>
        <%= f.email_field :email, class: "form-control"%>
    </div>
    <div class="mb-3">
        <%= f.label :password, class: "form-label"%>
        <%= f.text_field :password, class: "form-control"%>
    </div>
    <div class="mb-3">
        <%= f.label :password_confirmation, class: "form-label"%>
        <%= f.text_field :password_confirmation, class: "form-control"%>
    </div>
    <div class="d-grid justify-content-md-end">
        <%= f.submit class:"btn", id: "button"%>
    </div>
<% end %>